name: AMADEUS-RUN
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: INSTALL
        run: npm i

      - name: AMADEUS GO
        run: npm start
        
